services:
  - type: web
    name: qaraqalpaqnews
    env: python
    buildCommand: ""
    startCommand: gunicorn src.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: src.settings
